name: hwyd
description: hwyd is the world's first nano journal. Simple. Focused. Beautiful. All you'll want to do is write your heart out.
publish_to: 'none'
version: 1.6.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.0.5
  date_format: ^2.0.2
  file: ^6.1.4
  share_plus: ^7.2.1
  url_launcher: ^6.2.1
  cupertino_onboarding: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.3

flutter:
  assets:
    - assets/hwyd_logo.png
  uses-material-design: true
